spring.application.name=DSCommerce


#connection properties db h2 (memory datasource)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

#web client config
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Sql in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
